name: Test CI

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1

      - name: Build and run tests
        run: make build test
